drop table if exists ok911.address_point;
create table ok911.address_point (
    id serial primary key,
    geom geometry (point, 4326),
    discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
    revdate timestamp,  
    reveditor varchar(75),  
    effectdate timestamp,  
    expiredate timestamp,  
    nguid_add varchar(254), 
    country varchar(2) references ok911.country_tbl(country),
    state  varchar(2) references ok911.state_tbl(state), 
    county varchar(40) references ok911.county_tbl(county),
    city varchar(100), 
    addpre varchar(15), 
    address bigint, 
    addsuf varchar(15), 
    predir varchar(9) references ok911.predir_tbl(predir),
    premod varchar(15), 
    pretype varchar(50) references ok911.type_tbl(type),
    pretypesep varchar(20) references ok911.separator_tbl(pretypesep),
    street varchar(60), 
    streettype varchar(50) references ok911.type_tbl(type),
    sufdir varchar(9) references ok911.predir_tbl(predir),
    sufmod varchar(25), 
    esn varchar(5), 
    msagcomm varchar(30), 
    postcomm varchar(40), 
    zipcode varchar(7), 
    zipcode4 varchar(4), 
    bldgname varchar(75), 
    floor varchar(75), 
    bldgunit varchar(75), 
    room varchar(75), 
    seat varchar(75), 
    landmkname varchar(150), 
    addtnlloc varchar(225), 
    placetype varchar(50) references ok911.placetype_tbl(placetype),  
    longitude double precision, 
    latitude double precision, 
    elevation smallint, 
    label varchar(50), 
    milepost varchar(150), 
    adddatauri varchar(254), 
    uninccomm varchar(100), 
    submit varchar(1) references ok911.yesno_tbl(yesno),
    comment varchar(100), 
    rclmatch varchar(254), 
    rclside varchar(1) references ok911.rclside_tbl(rclside), 
    nbrhdcomm varchar(100), 
    grpquarter varchar(1) references ok911.yesno_tbl(yesno),
    occuptime varchar(50), 
    strmsheltr varchar(25) references ok911.strmsheltr_tbl(strmsheltr), 
    basement varchar(1) references ok911.yesno_tbl(yesno),
    lgcyadd varchar(100), 
    lgcypredir varchar(2) references ok911.lgcypredir_tbl(lgcypredir), 
    lgcystreet varchar(75), 
    lgcytype varchar(4) references ok911.lgcytype_tbl(type), 
    lgcysufdir varchar(2) references ok911.lgcypredir_tbl(lgcypredir), 
    fulladdr varchar(100), 
    fullname varchar(50), 
    psapg varchar(25), 
    placement varchar(25) references ok911.placement_tbl(placement),
    initisrce varchar(75), 
    initidate timestamp,  
    agency_id varchar(100) references ok911.agencyid_tbl(agencyid)
     );

create index address_idx on ok911.address_point using gist(geom);               


drop table if exists ok911.road_centerline;
create table ok911.road_centerline (
    id serial primary key,
    geom geometry (linestring, 4326),
    discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
    revdate timestamp,  
    reveditor varchar(75), 
    effectdate timestamp,  
    expiredate timestamp,  
    nguid_rdcl varchar(254), 
    agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
    country_l varchar(2) references ok911.country_tbl(country), 
    country_r varchar(2) references ok911.country_tbl(country), 
    state_l varchar(2) references ok911.state_tbl(state), 
    state_r varchar(2) references ok911.state_tbl(state), 
    county_l varchar(40) references ok911.county_tbl(county),
    county_r varchar(40) references ok911.county_tbl(county),
    city_l varchar(100), 
    city_r varchar(100), 
    add_l_pre varchar(15), 
    add_r_pre varchar(15), 
    add_l_from bigint, 
    add_l_to bigint, 
    add_r_from bigint, 
    add_r_to bigint, 
    parity_l varchar(1) references ok911.parity_tbl(parity),
    parity_r varchar(1) references ok911.parity_tbl(parity),
    postcomm_l varchar(40), 
    postcomm_r varchar(40), 
    zipcode_l varchar(7), 
    zipcode_r varchar(7), 
    zipcode4_l varchar(4), 
    zipcode4_r varchar(4), 
    esn_l varchar(5), 
    esn_r varchar(5), 
    psap_l varchar(25), 
    psap_r varchar(25), 
    msagcomm_l varchar(30), 
    msagcomm_r varchar(30), 
    premod varchar(15), 
    predir varchar(9) references ok911.predir_tbl(predir),
    pretype varchar(50) references ok911.type_tbl(type), 
    pretypesep varchar(20) references ok911.separator_tbl(pretypesep), 
    street varchar(60), 
    streettype varchar(50) references ok911.type_tbl(type),
    sufdir varchar(9) references ok911.predir_tbl(predir), 
    sufmod varchar(25), 
    label varchar(50), 
    speedlimit bigint, 
    oneway varchar(2) references ok911.oneway_tbl(oneway), 
    roadclass varchar(15) references ok911.roadclass_tbl(roadclass),
    fromlevel varchar(10) references ok911.roadlevel_tbl(level),
    tolevel varchar(10) references ok911.roadlevel_tbl(level),
    surface varchar(10), 
    boundlane varchar(9) references ok911.predir_tbl(predir),
    topoexcept varchar(20) references ok911.topoexcept_tbl(topoexcept), 
    submit varchar(1) references ok911.yesno_tbl(yesno),
    comment varchar(100), 
    uninccomml varchar(100), 
    uninccommr varchar(100), 
    nbrhdcomml varchar(100), 
    nbrhdcommr varchar(100), 
    initisrce varchar(75), 
    initidate timestamp,  
    altstname1 varchar(50), 
    lgcypredir varchar(2) references ok911.lgcypredir_tbl(lgcypredir), 
    lgcystreet varchar(75), 
    lgcytype varchar(4) references ok911.lgcytype_tbl(type),
    lgcysufdir varchar(2) references ok911.lgcypredir_tbl(lgcypredir),
    fullname varchar(50), 
    roadlength double precision, 
    drivetime double precision, 
    deadend varchar(1) references ok911.yesno_tbl(yesno),
    lanes varchar(5) references ok911.number_tbl(number), 
    toll varchar(1) references ok911.yesno_tbl(yesno),
    ltdaccess varchar(1) references ok911.yesno_tbl(yesno),
    geomsag_l varchar(1) references ok911.yesno_tbl(yesno),
    geomsag_r varchar(1) references ok911.yesno_tbl(yesno),
    valid_l varchar(1) references ok911.yesno_tbl(yesno), 
    valid_r varchar(1) references ok911.yesno_tbl(yesno)
	);

create index centerline_idx on ok911.road_centerline using gist(geom);               


drop table if exists ok911.esb_fire_boundary;
create table ok911.esb_fire_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	nguid_fire varchar(254), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	agency varchar(60), 
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn),
	serviceuri varchar(254), 
	servicenum varchar(15), 
	initisrce varchar(75), 
	initidate timestamp,  
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100)
        );

drop table if exists ok911.esb_law_boundary;
create table ok911.esb_law_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	nguid_law varchar(254), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	agency varchar(60), 
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn),
	serviceuri varchar(254), 
	servicenum varchar(15), 
	initisrce varchar(75), 
	initidate timestamp,  
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100) 
        );
 

drop table if exists ok911.esb_ems_boundary;
create table ok911.esb_ems_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	nguid_ems varchar(254), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	agency varchar(60), 
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn),
	serviceuri varchar(254), 
	servicenum varchar(15), 
	initisrce varchar(75), 
	initidate timestamp,  
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100)
        );

drop table if exists ok911.psap_boundary;
create table ok911.psap_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	nguid_psap varchar(254), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	agency varchar(60), 
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn),
	serviceuri varchar(254), 
	servicenum varchar(15), 
	initisrce varchar(75), 
	initidate timestamp,  
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100) 
        );

create index psap_idx on ok911.psap_boundary using gist(geom);               

drop table if exists ok911.municipal_boundary;
create table ok911.municipal_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,   
	reveditor varchar(75),  
	effectdate timestamp,  
	expiredate timestamp,  
	initisrce varchar(75),  
	initidate timestamp,  
	nguid_muni varchar(254), 
	state varchar(2) references ok911.state_tbl(state),
	county varchar(40) references ok911.county_tbl(county),
	city varchar(100), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100) 
	);

drop table if exists ok911.discrepancyagency_boundary;
create table ok911.discrepancyagency_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	initisrce varchar(75), 
	initidate timestamp,  
	nguid_disc varchar(254), 
	agency varchar(60), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn), 
	serviceuri varchar(254), 
	servicenum varchar(15), 
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state),
	submit varchar(1) references ok911.yesno_tbl(yesno),
	comment varchar(100)
        );


drop table if exists ok911.esz_boundary;
create table ok911.esz_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	initisrce varchar(75), 
	initidate timestamp,  
	nguid_esz varchar(254), 
	agency varchar(60), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn), 
	serviceuri varchar(254), 
	servicenum varchar(15), 
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state),
	submit varchar(1) references ok911.yesno_tbl(yesno),
	comment varchar(100),
	esn varchar(15), 
	esz varchar(15)
        );
