/*creating the tables with for tn911*/
/*rjhale                            */
/*20200924                          */

drop table if exists ok911.address_point;
create table ok911.address_point (
    id serial primary key,
    geom geometry (point, 4326),
    "DiscrpAgID" varchar(75) references ok911.agencyid_tbl(agencyid),
    "RevDate" timestamp,  
    "RevEditor" varchar(75),  
    "EffectDate" timestamp,  
    "ExpireDate" timestamp,  
    "NGUID_ADD" varchar(254), 
    "Country" varchar(2) references ok911.country_tbl(country),
    "State"  varchar(2) references ok911.state_tbl(state), 
    "County" varchar(40) references ok911.county_tbl(county),
    "City" varchar(100), 
    "AddPre" varchar(15), 
    "Address" bigint, 
    "AddSuf" varchar(15), 
    "PreDir" varchar(9) references ok911.predir_tbl(predir),
    "PreMod" varchar(15), 
    "PreType" varchar(50) references ok911.type_tbl(type),
    "PreTypeSep" varchar(20) references ok911.separator_tbl(pretypesep),
    "Street" varchar(60), 
    "StreetType" varchar(50) references ok911.type_tbl(type),
    "SufDir" varchar(9) references ok911.predir_tbl(predir),
    "SufMod" varchar(25), 
    "ESN" varchar(5), 
    "MSAGComm" varchar(30), 
    "PostComm" varchar(40), 
    "Zipcode" varchar(7), 
    "Zipcode4" varchar(4), 
    "BldgName" varchar(75), 
    "Floor" varchar(75), 
    "BldgUnit" varchar(75), 
    "Room" varchar(75), 
    "Seat" varchar(75), 
    "LandmKname" varchar(150), 
    "AddtnlLoc" varchar(225), 
    "PlaceType" varchar(50) references ok911.placetype_tbl(placetype),  
    "Longitude" double precision, 
    "Latitude" double precision, 
    "Elevation" smallint, 
    "Label" varchar(50), 
    "MilePost" varchar(150), 
    "AddDataURI" varchar(254), 
    "UnincComm" varchar(100), 
    "SUBMIT" varchar(1) references ok911.yesno_tbl(yesno),
    "Comment" varchar(100), 
    "RCLMatch" varchar(254), 
    "RCLSide" varchar(1) references ok911.rclside_tbl(rclside) 
    "NbrhdComm" varchar(100), 
    "GrpQuarter" varchar(1) references ok911.yesno_tbl(yesno),
    "OccupTime" varchar(50), 
    "StrmSheltr" varchar(25) references ok911.strmsheltr_tbl(strmsheltr), 
    "Basement" varchar(1) references ok911.yesno_tbl(yesno),
    "LgcyAdd" varchar(100), 
    "LgcyPreDir" varchar(2) references ok911.lgcypredir_tbl(lgcypredir), 
    "LgcyStreet" varchar(75), 
    "LgcyType" varchar(4) references ok911.lgcytype_tbl(type), 
    "LgcySufdir" varchar(2) references ok911.lgcypredir_tbl(lgcypredir), 
    "FullAddr" varchar(100), 
    "FullName" varchar(50), 
    "PSAP" varchar(25), 
    "Placement" varchar(25) references ok911.placement_tbl(placement),
    "InitiSrce" varchar(75), 
    "InitiDate" timestamp,  
    "Agency_ID" varchar(100) references ok911.agencyid_tbl(agencyid)
     );

create index address_idx ON ok911.address_point using gist(geom);               


drop table if exists ok911.road_centerline;
create table ok911.road_centerline (
    id serial primary key,
    geom geometry (linestring, 4326),
	dscrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	nguid_rdcl varchar(254), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid)
	fullname varchar(50), 
	label varchar(50), 
	add_l_pre varchar(15), 
	add_r_pre varchar(15), 
	add_l_from bigint, 
	add_l_to bigint, 
	add_r_from bigint, 
	add_r_to bigint, 




	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
#	nguid_rdcl varchar(254), 
	country_l varchar(2) references ok911.country_tbl(country), 
	country_r varchar(2) references ok911.country_tbl(country), 
	state_l varchar(2) references ok911.state_tbl(state), 
	state_r varchar(2) references ok911.state_tbl(state), 
	county_l varchar(40) references ok911.county_tbl(county),
	county_r varchar(40) references ok911.county_tbl(county),
	city_l varchar(100), 
	city_r varchar(100), 
#	add_l_pre varchar(15), 
#	add_r_pre varchar(15), 
#	add_l_from bigint, 
#	add_l_to bigint, 
#	add_r_from bigint, 
#	add_r_to bigint, 
	parity_l varchar(1) references ok911.parity_tbl(parity),
	parity_r varchar(1) references ok911.parity_tbl(parity),
	postcomm_l varchar(40), 
	postcomm_r varchar(40), 
	zipcode_l varchar(7), 
	zipcode_r varchar(7), 
	zipcode4_l varchar(4), 
	zipcode4_r varchar(4), 
	esn_l varchar(5), 
	esn_r varchar(5), 
	psap_l varchar(25), 
	psap_r varchar(25), 
	msagcomm_l varchar(30), 
	msagcomm_r varchar(30), 
	premod varchar(15), 
	predir varchar(9) references ok911.predir_tbl(predir),
	pretype varchar(50) references ok911.type_tbl(type), 
	pretypesep varchar(20) references ok911.separator_tbl(pretypesep), 
	street varchar(60), 
	streettype varchar(50) references ok911.type_tbl(type),
	sufdir varchar(9) references ok911.predir_tbl(predir), 
	sufmod varchar(25), 
#	label varchar(50), 
	speedlimit bigint, 
	oneway varchar(2) references ok911.oneway_tbl(oneway), 
	roadclass varchar(15) references ok911.roadclass_tbl(roadclass),
	fromlevel varchar(10) references ok911.roadlevel_tbl(level),
	tolevel varchar(10) references ok911.roadlevel_tbl(level),
	surface varchar(10), 
	boundlane varchar(9) references ok911.predir_tbl(predir),
	topoexcept varchar(20) references ok911.topoexcept_tbl(topoexcept), 
	submit varchar(1) references ok911.yesno_tbl(yesno),
	comment varchar(100), 
	uninccomml varchar(100), 
	uninccommr varchar(100), 
	nbrhdcomml varchar(100), 
	nbrhdcommr varchar(100), 
	initisrce varchar(75), 
	initidate timestamp,  
	altstname1 varchar(50), 
	altstname2 varchar(50), 
	altstname3 varchar(50), 
	lgcypredir varchar(2) references ok911.lgcypredir_tbl(lgcypredir), 
	lgcystreet varchar(75), 
	lgcytype varchar(4) references ok911.lgcytype_tbl(type),
	lgcysufdir varchar(2) references ok911.lgcypredir_tbl(lgcypredir),
#	fullname varchar(50), 
	roadlength double precision, 
	drivetime double precision, 
	deadend varchar(1) references ok911.yesno_tbl(yesno),
	lanes varchar(5) references ok911.number_tbl(number), 
	toll varchar(1) references ok911.yesno_tbl(yesno),
	ltdaccess varchar(1) references ok911.yesno_tbl(yesno),
	geomsag_l varchar(1) references ok911.yesno_tbl(yesno),
	geomsag_r varchar(1) references ok911.yesno_tbl(yesno),
	valid_l varchar(1) references ok911.yesno_tbl(yesno), 
	valid_r varchar(1) references ok911.yesno_tbl(yesno),
#	agency_id varchar(100) references ok911.agencyid_tbl(agencyid)
	);

create index centerline_idx ON ok911.road_centerline using gist(geom);               


drop table if exists ok911.esb_fire_boundary;
create table ok911.esb_fire_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	nguid_fire varchar(254), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	agency varchar(60), 
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn),
	serviceuri varchar(254), 
	servicenum varchar(15), 
	initisrce varchar(75), 
	initidate timestamp,  
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100)
        );

drop table if exists ok911.esb_law_boundary;
create table ok911.esb_law_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	nguid_law varchar(254), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	agency varchar(60), 
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn),
	serviceuri varchar(254), 
	servicenum varchar(15), 
	initisrce varchar(75), 
	initidate timestamp,  
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100) 
        );
 

drop table if exists ok911.esb_ems_boundary;
create table ok911.esb_ems_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	nguid_ems varchar(254), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	agency varchar(60), 
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn),
	serviceuri varchar(254), 
	servicenum varchar(15), 
	initisrce varchar(75), 
	initidate timestamp,  
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100)
        );

drop table if exists ok911.psap_boundary;
create table ok911.psap_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	nguid_psap varchar(254), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	agency varchar(60), 
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn),
	serviceuri varchar(254), 
	servicenum varchar(15), 
	initisrce varchar(75), 
	initidate timestamp,  
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100) 
        );

create index psap_idx ON ok911.psap_boundary using gist(geom);               

drop table if exists ok911.municipal_boundary;
create table ok911.municipal_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,   
	reveditor varchar(75),  
	effectdate timestamp,  
	expiredate timestamp,  
	initisrce varchar(75),  
	initidate timestamp,  
	nguid_muni varchar(254), 
	state varchar(2) references ok911.state_tbl(state),
	county varchar(40) references ok911.county_tbl(county),
	city varchar(100), 
	submit varchar(1) references ok911.yesno_tbl(yesno), 
	comment varchar(100) 
	);

drop table if exists ok911.discrepancyagency_boundary;
create table ok911.discrepancyagency_boundary (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	initisrce varchar(75), 
	initidate timestamp,  
	nguid_disc varchar(254), 
	agency varchar(60), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn), 
	serviceuri varchar(254), 
	servicenum varchar(15), 
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state),
	submit varchar(1) references ok911.yesno_tbl(yesno),
	comment varchar(100)
        );


drop table if exists ok911.esn;
create table ok911.esn (
    id serial primary key,
    geom geometry (polygon, 4326),
	discrpagid varchar(75) references ok911.agencyid_tbl(agencyid),
	revdate timestamp,  
	reveditor varchar(75), 
	effectdate timestamp,  
	expiredate timestamp,  
	initisrce varchar(75), 
	initidate timestamp,  
	nguid_esz varchar(254), 
	agency varchar(60), 
	agency_id varchar(100) references ok911.agencyid_tbl(agencyid),
	avcard_uri varchar(254), 
	serviceurn varchar(50) references ok911.serviceurn_tbl(serviceurn), 
	serviceuri varchar(254), 
	servicenum varchar(15), 
	country varchar(2) references ok911.country_tbl(country),
	state varchar(2) references ok911.state_tbl(state),
	submit varchar(1) references ok911.yesno_tbl(yesno),
	comment varchar(100),
	esn varchar(15), 
	esz varchar(15)
        );
